config/routes.rb
Rails.application.routes.draw do  
  root 'static#home'

  # Basic API endpoints
  get '/:controller/:id/data', action: 'data'
  get '/:controller/collection', action: 'collection'
  get '/users/:id/reviews' => 'users#reviews'
  get '/users/:id/views' => 'users#views'
  get '/cui' => 'application#current_user_info'

  # User Routes
  get '/signup' => 'users#new'
  resources :users, only: %i[show update create]
  resources :reviews, only: %i[create edit update destroy]
  resources :views, only: %i[create destroy]

  # Media Routes
  resources :media, only: %i[show]
  
  resources :movies, only: %i[index new create show]
  resources :series, only: %i[index new create show] do    
    resources :seasons, only: %i[new] do
      resources :episodes, only: %i[new]
    end
  end
  resources :seasons, only: %i[create show]
  resources :episodes, only: %i[create show]

  # Session Control
  get '/login' => 'sessions#new'
  post '/logout' => 'sessions#destroy'
  resources :sessions, only: %i[create]

  # Omniauth
  get '/auth/:provider/callback' => 'sessions#omni_create'

  # fallback
  match "*path", via: %i[get post], to: "application#handle_404"

end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_action :set_medium, only: %i[show data]

  def index; end

  def show
    case @medium.medium_type.downcase
    when 'movie'
      redirect_to movie_path(@medium.element)
    when 'series'
      redirect_to series_path(@medium.element)
    when 'season'
      redirect_to season_path(@medium.element)
    when 'episode'
      redirect_to episode_path(@medium.element)
    else
      redirect_back fallback_location: root_path, notice: 'Something has gone terribly wrong'
    end
  end

  def data
    render json: @medium
  end

  private

  def set_medium
    @medium = Medium.find_by(id: params[:id])
  end
end

app/views/media/_children.html.erb
<% if medium.try(:children) %>
  <h4><%= medium.children.first.class.name.pluralize %>:</h4>
  <% medium.children.each do |child| %>
    <div class='medium_child_<%=child.id%>'>
      <%= link_to child.title, medium_path(child.medium_id) %>      
    </div>
  <% end %>  
<hr>
<% else %>
  <p><%= medium.title %> has no <%= medium.class.name == 'Series' ? 'Seasons' : 'Episodes'  %>!</p>
<% end %>

app/views/media/_index.html.erb
<h1>Here are some <%= media.first.medium.medium_type.pluralize %>!</h1> 
<ul id='media-list' style='columns: 4'></ul>
<%= render '/media/prompt_new', medium_name: media.first.class.name, new_path: new_path %>

<script type='text/javascript' charset='utf-8'>
  url = new URL(this.document.URL);
  DataHandler.prototype.renderData(`${url.pathname}/collection`, 'index');  
</script>

app/views/media/_parent.erb
<% if medium.try(:parent) %>
<hr>
  <div id='medium_parent_<%=medium.parent.id%>'>
  A member of <%= medium.parent.class.name %>: <%= link_to medium.parent.title, medium_path(medium.parent.medium_id) %>      
  </div>
<hr>
<% end %>

app/views/media/_prompt_new.html.erb
<p>Don't see your <%= medium_name %>?</p> 
<p><%= link_to "Add a #{medium_name}!", new_path %></p>

app/views/media/_show.html.erb
<article id='medium'>  
  <section id='data'>
    <h2 id='title'></h2>
    <section id='parent'></section>
    <section id='children'></section> 
    <section id='reviews'></section> 
  </section>
  <section id='actions'>
    <div id='add-child'>
      <% unless medium.class.name == 'Movie' || medium.class.name == 'Episode' %>
        <% if medium.class.name == 'Series' %>
          <%= render '/media/prompt_new', medium_name: 'Season', new_path: new_series_season_path(series_id: medium.id) %>
        <% else %>
          <%= render '/media/prompt_new', medium_name: 'Episode', new_path: new_series_season_episode_path(series_id: medium.parent.id, season_id: medium.id) %>
        <% end %>
      <% end %>
    </div>
    <% if logged_in? %>
      <div id='add-view'>
        <% unless current_user.views.any? { |view| view.medium_id == medium.medium_id } %>
          <%= render 'views/new_view', view: View.new, medium_id: medium.medium_id %>
        <% end %>
      </div>
      <div id='add-review'>        
        <h4>Review this <%= medium.medium.medium_type %>!</h4>
        <%= render 'notice' %>
        <%= render 'reviews/form', review: Review.new, medium_id: medium.medium_id %>
      </div>
    <% else %>
      <p>Log in to add a review!</p>
    <% end %>
  </section>
</article>

<script type='text/javascript' charset='utf-8'>
  url = new URL(this.document.URL);
  DataHandler.prototype.renderData(`${url.pathname}/data`);  
</script>

<script type="text/javascript" charset="utf-8">  
  form_field = document.getElementById('new_review');
  if (form_field) {
    form_field.addEventListener('submit', event => {
      event.preventDefault();
      review_form = new FormData(form_field);      
      DataHandler.prototype.submitData('/reviews', review_form, form_field);
    });
  }
</script>