config/routes.rb
Rails.application.routes.draw do  
  root 'static#home'

  # Basic API endpoints
  get '/:controller/:id/data', action: 'data'
  get '/:controller/collection', action: 'collection'
  get '/users/:id/reviews' => 'users#reviews'
  get '/users/:id/views' => 'users#views'
  get '/cui' => 'application#current_user_info'

  # User Routes
  get '/signup' => 'users#new'
  resources :users, only: %i[show update create]
  resources :reviews, only: %i[create edit update destroy]
  resources :views, only: %i[create destroy]

  # Media Routes
  resources :media, only: %i[show]
  
  resources :movies, only: %i[index new create show]
  resources :series, only: %i[index new create show] do    
    resources :seasons, only: %i[new] do
      resources :episodes, only: %i[new]
    end
  end
  resources :seasons, only: %i[create show]
  resources :episodes, only: %i[create show]

  # Session Control
  get '/login' => 'sessions#new'
  post '/logout' => 'sessions#destroy'
  resources :sessions, only: %i[create]

  # Omniauth
  get '/auth/:provider/callback' => 'sessions#omni_create'

  # fallback
  match "*path", via: %i[get post], to: "application#handle_404"

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
  before_action :set_review, only: %i[destroy edit update]
  before_action :set_user, only: %i[index]
  before_action :require_owner, only: %i[destroy edit update]
  before_action :require_login, only: %i[create]

  def index
    @reviews = @user.reviews
  end  

  def create
    review = Review.new(review_params)
    review.medium = Medium.find(params[:medium_id])
    review.save
    redirect_to medium_path(review.medium)
  end

  def edit; end

  def update
    @review.update(review_params)
    redirect_to medium_path(@review.medium)
  end

  def destroy
    @review.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def require_owner
    return head(:forbidden) unless current_user == @review.reviewer
  end

  def set_review
    @review = Review.find_by(id: params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_user, only: %i[index]
  before_action :set_review, only: %i[destroy edit update data]
  before_action :require_login, only: %i[create]
  before_action :require_owner, only: %i[destroy edit update]
  skip_before_action :verify_authenticity_token, only: %i[destroy]

  def index
    @reviews = @user.reviews
  end

  def create
    review = Review.new(review_params)
    # If this fails, view already exists
    View.create(viewer: review.reviewer, medium: review.medium)
    if review.save
      render json: review, status: 201
    else
      render json: { errors: review.errors.full_messages }, status: 400
    end
  end

  def edit; end

  def update
    @review.update(review_params)
    return redirect_to edit_review_path(@review), notice: @review.errors unless @review.errors.blank?

    redirect_to medium_path(@review.medium)
  end

  def destroy
    @review.destroy
    if @review.destroyed?
      head :accepted
    else
      head :bad_request
    end
  end

  def data
    render json: @review
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :medium_id, :user_id)
  end

  def require_owner
    return head(:forbidden) unless current_user == @review&.reviewer
  end

  def set_review
    @review = Review.find_by(id: params[:id])
  end
end

app/views/reviews/_form.html.erb
<%= form_for review do |f| %>
  <%= f.hidden_field :medium_id, value: medium_id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :content, 'Content:' %><br>
  <%= f.text_field :content %><br>
  <%= f.label :rating, 'rating:' %><br>
  <%= f.select :rating, (1..5) %><br>
  <%= f.submit id: 'submit' %>
<% end %>

app/views/reviews/_owner_actions.html.erb
<% if review.reviewer == current_user %>
  <div class='current_user_actions_review_<%=review.id%>'>
    <%= link_to  "Edit Review", edit_review_path(review) %>
    <%= form_tag review_path(review), method: 'delete' do %>
      <%= submit_tag 'Delete Review'%>
    <% end %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review for <%= link_to @review.medium.element.title, medium_path(@review.medium) %></h1>
<%= render 'notice' %>
<%= render 'form', review: @review, medium_id: @review.medium_id %>